# Generated by Django 4.2.14 on 2024-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
            ],
        ),
    ]
